outdated:
	clojure -Aoutdated --aliases outdated --aliases handler
update-clj:
	clojure -Aoutdated --aliases outdated --aliases handler --write

uberjar:
	lein uberjar
	cp target/uberjar/geckocomplete-*-standalone.jar geckocomplete.jar
